<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_HmiWatchdog" Id="{df81b304-bd24-448b-8153-41afa23e1505}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HmiWatchdog
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>