<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_ModeManager" Id="{7a40fef7-3e28-40a4-a30e-b65c523ee72e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ModeManager
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>