<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_InitializationSequence" Id="{e893420c-05db-404b-b76d-573468292b63}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_InitializationSequence
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>