<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_LoadingSequence" Id="{1353c084-c4cd-44a2-a00e-480bb357bf7f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LoadingSequence
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>